name: HelloAndroidBuild
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: "8"
          distribution: 'zulu'
      - name: Build with Gradle
        uses: gradle/actions@v5.0.0
      - name: Upload a Build Artifact
        run: ./gradlew build
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk
